import {
  GolfGameDefinition,
  ScoringFormat,
  GameplayFormat,
  MatchupFormat,
  BettingMode,
} from "./types";

export const gameDefinitions: GolfGameDefinition[] = [
  // ─── Ready games ──────────────────────────────────────────────────────────────
  {
    id: "stroke-play-game",
    name: "Stroke Play",
    description: "Lowest total strokes over 18 holes wins. The classic format.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Classic", "Individual"],
    engineStatus: "ready",
  },
  {
    id: "match-play-game",
    name: "Match Play",
    description: "Win holes, not strokes. Most holes won takes the match.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 2,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Classic", "H2H"],
    engineStatus: "ready",
  },
  {
    id: "nassau",
    name: "Nassau",
    description:
      "Three bets in one: front 9, back 9, and overall — each a separate match play competition settled independently.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Nassau,
    minPlayers: 2,
    maxPlayers: 2,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Betting", "H2H", "Classic"],
    engineStatus: "ready",
  },
  {
    id: "skins-game",
    name: "Skins",
    description:
      "Each hole is worth a skin. Ties carry the skin to the next hole — pressure builds fast.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Skins,
    minPlayers: 2,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Betting", "Per Hole", "Multi-Player"],
    engineStatus: "ready",
  },
  {
    id: "stableford",
    name: "Stableford",
    description:
      "Score points per hole relative to par: Eagle=4, Birdie=3, Par=2, Bogey=1, Double+=0. Most points wins.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Individual", "Fun"],
    engineStatus: "ready",
  },
  {
    id: "team-best-ball",
    name: "Best Ball",
    description:
      "Teams of 2. Each player plays their own ball — the best score on each hole counts for the team.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "2v2"],
    engineStatus: "ready",
  },
  {
    id: "scramble-game",
    name: "Scramble",
    description:
      "All players tee off, best shot is selected, and everyone plays from that spot. Repeat until holed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Scramble,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Fun", "Scramble"],
    engineStatus: "ready",
  },

  // ─── Stub games (coming soon) ─────────────────────────────────────────────────
  {
    id: "match-play-team",
    name: "Team Match Play",
    description:
      "Two teams compete hole-by-hole in match play. Each team's best net score on a hole wins the hole for the team.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "Match Play", "H2H"],
    engineStatus: "stub",
  },
  {
    id: "wolf",
    name: "Wolf",
    description:
      "Each hole one player is the Wolf — they can pick a partner after each tee shot or go alone. Points awarded per hole based on outcome.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Strategy", "Per Hole", "4 Players"],
    engineStatus: "stub",
  },
  {
    id: "bingo-bango-bongo",
    name: "Bingo Bango Bongo",
    description:
      "Three points up for grabs each hole: first on the green (Bingo), closest to the pin when all are on (Bango), and first in the hole (Bongo).",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 3,
    maxPlayers: 6,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Per Hole", "Fun"],
    engineStatus: "stub",
  },
  {
    id: "chicago",
    name: "Chicago",
    description:
      "Points-based game where each player has a quota based on their handicap. Score points above par relative to your quota — highest total wins.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Handicap", "Individual"],
    engineStatus: "stub",
  },
  {
    id: "alt-shot",
    name: "Alternate Shot",
    description:
      "Teams of 2 alternate hitting the same ball — one player tees off, the other plays the next shot. Strategy and chemistry required.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.AltShot,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Alternate Shot", "Classic"],
    engineStatus: "stub",
  },
  {
    id: "vegas",
    name: "Vegas",
    description:
      "Two-man teams combine their scores into a two-digit number each hole. Lower team score wins points — wild swings guaranteed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Betting", "2v2"],
    engineStatus: "stub",
  },
  {
    id: "shamble-game",
    name: "Shamble",
    description:
      "Everyone tees off, then the best drive is selected. Each player plays their own ball from that spot until holed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Shamble,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "Fun", "Shamble"],
    engineStatus: "stub",
  },
  {
    id: "ryder-cup",
    name: "Ryder Cup",
    description:
      "The ultimate team competition. Matches rotate between foursomes, fourball, and singles — points accumulate across the full event.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 24,
    bettingEnabled: false,
    handicapEnabled: true,
    tags: ["Team", "Tournament", "Prestige"],
    engineStatus: "stub",
  },
];
