import {
  GolfGameDefinition,
  ScoringFormat,
  GameplayFormat,
  MatchupFormat,
  BettingMode,
} from "./types";

export const gameDefinitions: GolfGameDefinition[] = [
  // ─── Ready games ──────────────────────────────────────────────────────────────
  {
    id: "stroke-play-game",
    name: "Medal Play (Stroke Play)",
    description:
      "Lowest total strokes over 18 holes wins. Play solo to track your round, or compete head-to-head.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 1,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Classic", "Individual"],
    engineStatus: "ready",
    supportedFormats: [
      {
        gameplayFormat: GameplayFormat.Individual,
        matchupFormat: MatchupFormat.Solo,
        minPlayers: 1,
        maxPlayers: 1,
        label: "Solo Round",
      },
      {
        gameplayFormat: GameplayFormat.Individual,
        matchupFormat: MatchupFormat.H2H,
        minPlayers: 2,
        maxPlayers: 8,
        label: "Individual vs Individual",
      },
    ],
  },
  {
    id: "match-play-game",
    name: "Match Play",
    description: "Win holes, not strokes. Most holes won takes the match.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 2,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Classic", "H2H"],
    engineStatus: "ready",
  },
  {
    id: "stableford",
    name: "Stableford",
    description:
      "Score points per hole relative to par: Eagle=4, Birdie=3, Par=2, Bogey=1, Double+=0. Most points wins.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 1,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Individual", "Fun"],
    engineStatus: "ready",
    supportedFormats: [
      {
        gameplayFormat: GameplayFormat.Individual,
        matchupFormat: MatchupFormat.Solo,
        minPlayers: 1,
        maxPlayers: 1,
        label: "Solo Round",
      },
      {
        gameplayFormat: GameplayFormat.Individual,
        matchupFormat: MatchupFormat.H2H,
        minPlayers: 2,
        maxPlayers: 8,
        label: "Individual vs Individual",
      },
    ],
  },
  {
    id: "team-best-ball",
    name: "Best Ball",
    description:
      "Teams of 2. Each player plays their own ball — the best score on each hole counts for the team.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "2v2"],
    engineStatus: "ready",
  },
  {
    id: "scramble-game",
    name: "Scramble",
    description:
      "All players tee off, best shot is selected, and everyone plays from that spot. Repeat until holed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Scramble,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Fun", "Scramble"],
    engineStatus: "ready",
  },

  // ─── Stub games (coming soon) ─────────────────────────────────────────────────
  {
    id: "match-play-team",
    name: "Team Match Play",
    description:
      "Two teams compete hole-by-hole in match play. Each team's best net score on a hole wins the hole for the team.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "Match Play", "H2H"],
    engineStatus: "stub",
  },
  {
    id: "wolf",
    name: "Wolf",
    description:
      "Each hole one player is the Wolf — they can pick a partner after each tee shot or go alone. Points awarded per hole based on outcome.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Strategy", "Per Hole", "4 Players"],
    engineStatus: "stub",
  },
  {
    id: "bingo-bango-bongo",
    name: "Bingo Bango Bongo",
    description:
      "Three points up for grabs each hole: first on the green (Bingo), closest to the pin when all are on (Bango), and first in the hole (Bongo).",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 3,
    maxPlayers: 6,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Per Hole", "Fun"],
    engineStatus: "stub",
  },
  {
    id: "chicago",
    name: "Chicago",
    description:
      "Points-based game where each player has a quota based on their handicap. Score points above par relative to your quota — highest total wins.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Points", "Handicap", "Individual"],
    engineStatus: "stub",
  },
  {
    id: "alt-shot",
    name: "Alternate Shot",
    description:
      "Teams of 2 alternate hitting the same ball — one player tees off, the other plays the next shot. Strategy and chemistry required.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.AltShot,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Alternate Shot", "Classic"],
    engineStatus: "stub",
  },
  {
    id: "modified-alt-shot",
    name: "Modified Alternate Shot",
    description:
      "A team format where all players tee off, the best drive is selected, then partners alternate shots until holed. Combines the strategy of alternate shot with a more forgiving start.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.ModifiedAltShot,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Alternate Shot", "Scramble"],
    engineStatus: "stub",
  },
  {
    id: "vegas",
    name: "Vegas",
    description:
      "Two-man teams combine their scores into a two-digit number each hole. Lower team score wins points — wild swings guaranteed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Team", "Betting", "2v2"],
    engineStatus: "stub",
  },
  {
    id: "shamble-game",
    name: "Shamble",
    description:
      "Everyone tees off, then the best drive is selected. Each player plays their own ball from that spot until holed.",
    scoringFormat: ScoringFormat.StrokePlay,
    gameplayFormat: GameplayFormat.Shamble,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 8,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "Fun", "Shamble"],
    engineStatus: "stub",
  },
  {
    id: "snake",
    name: "Snake",
    description:
      "The last player to 3-putt holds the Snake. The holder at the end of the round pays the group.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Putting", "Side Game", "Fun"],
    engineStatus: "stub",
  },
  {
    id: "hollywood",
    name: "Hollywood",
    description:
      "A 4-player rotating partners game. Players rotate partners every 6 holes — best ball within each pairing.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: true,
    tags: ["Team", "Rotating Partners", "4 Players"],
    engineStatus: "stub",
  },
  {
    id: "9-ball",
    name: "9-Ball",
    description:
      "A competitive points game played across 9-hole segments. Full rules coming soon.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Points", "Per Hole"],
    engineStatus: "stub",
  },
  {
    id: "dots",
    name: "Dots",
    description:
      "Players earn dots for on-course achievements (birdies, long drives, closest to pin). Most dots wins.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Points", "Achievements", "Custom"],
    engineStatus: "stub",
  },
  {
    id: "rabbit",
    name: "Rabbit",
    description:
      "Win a hole to grab the Rabbit — but you must win the next hole to keep it. Holder at the end wins.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Match Play", "Per Hole", "Streak"],
    engineStatus: "stub",
  },
  {
    id: "hammer",
    name: "Hammer",
    description:
      "Any player can call 'Hammer' mid-hole to double the bet. Opponent accepts or concedes the hole.",
    scoringFormat: ScoringFormat.MatchPlay,
    gameplayFormat: GameplayFormat.Individual,
    matchupFormat: MatchupFormat.H2H,
    bettingMode: BettingMode.Standard,
    minPlayers: 2,
    maxPlayers: 4,
    bettingEnabled: true,
    handicapEnabled: false,
    tags: ["Betting", "Match Play", "Aggressive"],
    engineStatus: "stub",
  },
  {
    id: "ryder-cup",
    name: "Ryder Cup",
    description:
      "The ultimate team competition. Matches rotate between foursomes, fourball, and singles — points accumulate across the full event.",
    scoringFormat: ScoringFormat.PointsBased,
    gameplayFormat: GameplayFormat.BestBall,
    matchupFormat: MatchupFormat.TeamPlay,
    bettingMode: BettingMode.Standard,
    minPlayers: 4,
    maxPlayers: 24,
    bettingEnabled: false,
    handicapEnabled: true,
    tags: ["Team", "Tournament", "Prestige"],
    engineStatus: "stub",
  },
];
